version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: literaryhelper-postgres
    environment:
      POSTGRES_DB: literaryhelper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./apps/frontend/db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - literaryhelper-network

  redis:
    image: redis:7-alpine
    container_name: literaryhelper-redis
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - literaryhelper-network

networks:
  literaryhelper-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
